#!/bin/bash -e
echo build idris worker
esbuild src/worker.ts --bundle --format=esm > public/worker.js
(
    install -d idris
    cd idris
    if [ ! -f idris2-js.zip ]; then
        echo fetch javascript idris
        wget https://github.com/dunhamsteve/idris2-js/releases/download/0.8.0/idris2-js.zip
        unzip idris2-js.zip
    fi
    VER=$(ls .idris2-js|grep idris)
    cp .idris2-js/bin/idris2.js idris2.js
    cp -r  .idris2-js/$VER/{prelude,base,contrib}*/2025* .
    install -d $VER/support/
    cp -r .idris2-js/$VER/support/js $VER/support
    zip -r files.zip idris2-* 2025*
    (
        echo "let {__mainExpression_0,runCommand}=(function(){"
        cat idris2.js
        cat ../patch.js
        echo "return {__mainExpression_0, runCommand}})()"    
    ) |grep -v '^#' | grep -v 'try{__mainExpression_0' > idris2.edit.js
)
cp -r samples/* public
cp idris/files.zip public
esbuild --minify idris/idris2.edit.js > public/idris2.js
